### ISSUE TITLE
Use custom ontologies

### ISSUE THREAD

**Issue by maarten-devries** [laminlabs/bionty-base#154]
Thank you for the amazing package and the rapid progress!

A suggestion: it would be very useful if I could create my own subclass of `EntityTable` for my own ontology, be it public or custom. 

Since #143, an Ontology class can only be instantiated if there is an ontology file specified in the `versions.yaml` file. 

Again, I want to use an ontology that's not in  `versions.yaml`.

Previously (in `bionty==0.5.1`) one could do this as follows: 

```
class CellLine(EntityTable):
    """Cell Line
    """
    def __init__(self, id=None, reload: bool = False) -> None:
        super().__init__(id=id)
        self._reload = reload
        self._filepath = None

    @cached_property
    def ontology(self):
        url = 'http://purl.obolibrary.org/obo/clo.owl'
        ontology_ = self._Ontology(handle=self._filepath, url=url)
        return ontology_
```

Happy to help think about how to add this functionality.

**Comment by sunnyosun** [comment]
Hello,

Thank you for trying out bionty! We are rapidly iterating on version management and will soon converge on a more robust solution integrated with lamindb in the next release.

In the current release, `versions.yaml` is a centralized reference file for all database versions. (Will be removed from github in the following PR and be a local file so that you won't get a conflict.) `_versions.yaml` specifies the in-use version.

To use a custom ontology, in your example, you can add the url to the `versions.yaml`:
```
CellLine:
  clo:
    versions:
      2.1.178: http://purl.obolibrary.org/obo/clo.owl
```

In the `versions/_versions.yaml` file, specify the in-use version by adding:
```
CellLine:
  clo: 2.1.178
```

After doing the above, you can now create your CellLine entity:
```
class CellLine(bt.EntityTable):
    """Cell line."""

    def __init__(
        self,
        id: str = "ontology_id",
        database: Optional[str] = None,
        version: Optional[str] = None,
    ) -> None:
        database = "clo" if database is None else database
        super().__init__(id=id, database=database, version=version)

    @cached_property
    def ontology(self) -> Ontology:  # type:ignore
        """Cell Line Ontology."""
        return super().ontology()
```

**Comment by maarten-devries** [comment]
Thank you for your reply!

So if I understand correctly, right now I'm required to fork the package in order to update `versions.yaml`. 
In a future release, I can use a local version of this file - I.e. I can specify my desired ontologies locally and use it without needing to fork `bionty`?

**Comment by falexwolf** [comment]
Thanks for trying Bionty & providing feedback, Maarten!

It's the night for @sunnyosun currently, so I'll answer for now - I think Sunny wants to refactor this part very soon (within days), so that you'll have a natural way of interfacing your ontology.

For context: Bionty is still not production grade (<1.0.0, no announcement yet). While it has high coverage, quality code and a good part of the API seems settled, we're still making some design decisions, which comes with (hopefully few remaining) breaking changes. It'll be transparent from the changelog. We should probably put up a warning banner...

**Comment by maarten-devries** [comment]
Thank you very much, Alex! 
I totally understand you're rapidly iterating. Hopefully it's still helpful to have some early users play around with the package.
Keep up the great work - you're solving a really important problem for this industry!

**Comment by sunnyosun** [comment]
Hi Maarten,

Yes, exactly! The yaml file will only serve as a starting template, and users can modify it for their ontologies. If you don’t mind, we’d ping you on our next release in a few days :)

Thank you again for this issue! Any suggestions for the package are always welcome!

~Sunny
