### ISSUE TITLE
API designs for switching databases

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#204]
1) (Current):
```
lookup = bt.Disease(database="mondo", version="2022-10-11").lookup
lookup.chronic_kidney_disease

# if nothing is passed, will read from `_current.yaml`
lookup = bt.Disease().lookup
```

2) essentially provides a lookup for the databases through the entity API:
```
lookup = bt.Disease.Mondo(version="2022-10-11").lookup
lookup.chronic_kidney_disease

# if no database is specified, same as 1)?
lookup = bt.Disease().lookup
```

@Zethson @falexwolf what do you think?

**Comment by Zethson** [comment]
I've personally never been a fan of such accesses (option 2) because they're less explicit. Other people reading the code will know for option 1 that the Mondo database is being accessed while option 2 doesn't really tell you what Mondo is.

Overall though, I don't have a strong opinion on this suggestion though. So whatever you prefer!

**Comment by falexwolf** [comment]
I'd prefer option (1) for the same reason as Lukas. I think (2) is also a bit nested.

(I assume "such accesses" refers to option 2.)
