### ISSUE TITLE
Need a way to clean up half downloaded files

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#246]
<img width="1063" alt="Screenshot 2023-03-10 at 20 38 10" src="https://user-images.githubusercontent.com/38218185/224318135-1fd4838a-5131-4fb3-ac4f-972ca8c37b1b.png">

**Comment by Zethson** [comment]
Related to https://github.com/laminlabs/bionty/issues/186

**Comment by Zethson** [comment]
Which solution do you envision? A couple of options

1. On startup we verify md5s and if they don't match we delete the files. Might be too expensive because we might have to check quite a few md5s.
2. We only check md5s when we're actually trying to access the respective owl file and warn if it doesn't match.
3. A clean function that removes everything that doesn't look complete/verifies all md5s?

**Comment by sunnyosun** [comment]
I think 2 might be the best. Since most of the time only the parquet file will be accessed, we just need to ensure the owl file is correct when the parquet file is written.
