### ISSUE TITLE
Add GENCODE to `Gene` source

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#527]
https://www.gencodegenes.org/

**Comment by Zethson** [comment]
We looked into it.

Summary:


1. GENCODE IDs are ENSEMBL IDs.
2. GENCODE IDs are a subset of ENSEMBL with a focus on human and mouse genes. These genes are manually reviewed and more curated.
3. We may consider using `GENCODE` as a `source` which is just a subset of `ensembl`.
4. A boolean column implying whether a ENSEMBL ID is a part of GENCODE is currently not planned because different users might not set it at the same time
